# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: '' # the subpath of your site, e.g. /blog
url: "https://r0m1t.com" # the base hostname & protocol for your site, e.g. http://example.com

#######################################################################
# Settings related to the Header and your About page go here,such as 
# your name, site name, profile pic, site tagline, your bio, 
# your social media links etc
#######################################################################

heading: Romit
subheading: # subheading won't work without a tagline, 
          # tagline is mandatory if you want the 
          # suheading to appear. The reason is
          # having a heading and a subheading looks 
          # ridiculous.
  enabled: true
  name: My second brain
tagline: # subheading won't work without a tagline, 
         # tagline is mandatory if you want the 
         # suheading to appear. The reason is
         # having a heading and a subheading looks 
         # ridiculous.
         # Although you can have the tagline without 
         # the subheading to support the main heading
         # which in this case is 'Knowledge Continuum'
  enabled: true
  name: Thoughtful ramblings and developing ideas
copyright:
  year: null
  msg: null # This is a mandatory attribute for copyright to be displayed
feedback: https://forms.gle/LZDsJd9j26dVVua26

user:
  display: true # setting it to false will remove the header image and bio
                # Note that user settings come wholesale, it does not have the 
                # granular enabling or disabling as with the 'preferences'
                # or the site-wide settings.
  name: Romit
  bio: Data guy
  photo: "/assets/images/memoji.PNG"
  social: # just leave the field blank or type in null, if you don't have a
          # particular social media account and it won't appear
    enabled: true # turn this to true
    twitter: romitjain_
    github: romitjain
    youtube: null
    linkedin: null
    twitch: null
    facebook: null 
    instagram: null

#####################################################################
# Settings related to your preferences go here, such as the
# search results, wiki-style-links, sidenotes, marginnotes, 
# transclusion, pagepreview, backlinks, related posts, highlighting, 
# context menu, flashcards, sliding window, wrapping
#####################################################################
preferences:
  search:
    enabled: true
    shortcut_hint:
        enabled: true
  wiki_style_link: # This property handles wiki style links '[['
    enabled: true
  sidenotes:
    enabled: true
  transclusion:
    enabled: true
  image:
    enabled: true
  pagepreview:
    enabled: true
  highlighting:
    enabled: true
    color: DAEDFF # Takes hexadecimal and basic names like white, red, etc.
                  # Do not add '#'(the pound symbol) before the hexadecimal number.
                  # In yml, it is considered as a comment
  backlinks:
    enabled: true
  related:
    enabled: true # This enables the posts that are related to each other by tags
  wrapping:
    enabled: true
  contextmenu:
    enabled: true
    copylink:
      enabled: true
    newtab:
      enabled: true
    backlinks:
      enabled: true
    related:
      enabled: true
  flashcards:
    enabled: true

encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
  # - jekyll-tagories

# Google Analytics
ga_tracking: G-6ZV2L9PZTN
ga_tracking_anonymize_ip: true

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname:

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ['apos', 'apos', 'quot', 'quot']
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
  notes:
    permalink: "/:collection/:path/"
    output: true

defaults:
  - scope:
      path: "posts"
      type: posts
    values:
      layout: Post
      permalink: /:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: Notes
      content-type: notes

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: ['old_website', '_comming_soon']

# last_edit_time_format: "%d %b %Y"
# last_modified_date: 12 Mar 2022